Repository openshift-eng/ocp-build-data-validator, pull requests merged in 2019-10, with the labels that each got.

#1 Move from GitLab to GitHub
  .gitlab-ci.yml
  Jenkinsfile
  README.rst
  setup.py
  tests/__init__.py
  tests/test_distgit.py
  tests/test_format.py
  tests/test_github.py
  tests/test_schema/__init__.py
  tests/test_schema/test_image_schema.py
  tests/test_schema/test_rpm_schema.py
  tests/test_schema/test_schema.py
  tests/test_support.py
  tox.ini
  validator/__init__.py
  validator/__main__.py
  validator/distgit.py
  validator/format.py
  validator/github.py
  validator/schema/__init__.py
  validator/schema/image_schema.py
  validator/schema/rpm_schema.py
  validator/support.py
Labels: size/XXL

#2 Only attempt to comment on PR if there is a PR
  Jenkinsfile
Labels: size/XS

#3 ART-1112: Add new modification action `add`
  tests/test_schema/test_modification_schema.py
  validator/schema/image_schema.py
  validator/schema/modification_schema.py
  validator/schema/rpm_schema.py
Labels: size/M

#5 Accept vars in distgit > branch values
  tests/test_distgit.py
  validator/distgit.py
Labels: lgtm, size/S
